version: '3'
services:
        rukovoditel:
                image: registriren/rukovoditel:latest
                volumes:
                        - RukovoditelWEB:/var/www/html
                networks:
                        - RukovoditelNET
                ports:
                        - "8008:80"
        mariadb:
                image: mariadb
                volumes:
                        - RukovoditelDB:/var/lib/mysql
                networks:
                        - RukovoditelNET
                ports:
                        - "3306:3306"
                environment:
                        - MYSQL_ROOT_PASSWORD=secret
                        - MYSQL_USER=ruser
                        - MYSQL_PASSWORD=secret
                        - MYSQL_DATABASE=rukovoditel
volumes:
        RukovoditelWEB:
        RukovoditelDB:
networks:
        RukovoditelNET:
